cau-bootcamp/wehavit

lib/common/routers/route_provider.dart
lib/features/effects/animation_sample_page.dart
lib/features/effects/text_animation/text_bubble_manager.dart
lib/features/effects/text_animation/text_bubble_widget.dart

1. 텍스트 반응 애니메이션 구상 (현재 디자인 없음)
2. 텍스트 반응 애니메이션 구현
3. 사용 방법 정리
- #77 
- #86
시간이 지나면 사라지거나, 말풍선을 탭하면 즉시 사라지는 애니메이션이 나오도록 구현해두었음.
- 이전에 PR 올린 Photo Animation과 유사한 형식으로 작성하였음
- 디자인이 나오면 요 기능은 대폭 갈아엎게 될 수 있기 때문에, 간단하게 반응을 볼 수 있는 기능만 구현해두었음.
- 기능 머지 화이팅!
Close 
#77 #86

[#86] feat: 텍스트 반응 애니메이션 구현

---

lib/common/constants/firebase_field_name.dart
lib/features/live_writing/data/repositories/live_writing_friend_repository_impl.dart
lib/features/live_writing/data/repositories/live_writing_mine_repository_impl.dart
lib/features/swipe_view/data/datasource/reaction_datasource_impl.dart

두 가지의 수정이 있습니다.
친구 신청 상태를 확인하는 코드를 삭제했습니다. (미사용)
- ReactionModel의 오타를 수정했습니다.
- Complementer -> Comlimenter
Close: #129

[#129] fix: reaction model typo and friend status filitering

---

lib/common/constants/firebase_field_name.dart
lib/features/my_page/data/datasources/resolution_datasource.dart
lib/features/my_page/data/datasources/resolution_remote_datasource_impl.dart
lib/features/my_page/data/entities/resolution_entity.dart
lib/features/my_page/data/repositories/resolution_repository_impl.dart
lib/features/my_page/domain/models/resolution_model.dart
lib/features/my_page/domain/repositories/resolution_repository.dart
lib/features/my_page/domain/usecases/get_confirm_post_list_for_resolution_id.dart
lib/features/my_page/presentation/providers/add_resolution_provider.dart
lib/features/my_page/presentation/providers/my_page_resolution_list_provider.dart
lib/features/my_page/presentation/screens/my_page_screen.dart
lib/features/my_page/presentation/widgets/resolution_dashboard_widget.dart
lib/features/my_page/presentation/widgets/resolution_doughnut_graph_widget.dart
lib/features/my_page/presentation/widgets/resolution_linear_gauge_graph_widget.dart

1. 그래프에 넣을 데이터 가공 방식 구상하기
2. 데이터 fetch 해와서 데이터 가공하기
3. 가공한 데이터 그래프에 전달해, 화면에 그려주기
- #22 
- #119 
데이터가 없는 경우에는 위 글처럼 아무런 그래프에 데이터가 없음
데이터가 있는 경우에는 아래 글처럼 그래프에 데이터가 그려짐
(아래 그래프에서는 최근 14일 중 [3, 4, 9]일 전에 인증을 남겼음)
- 언제를 기준으로 구간을 자를지에 대한 기획적인 논의가 필요할 것 같아서, 우선은 **[오늘\~14일) / [14일\~28일) 2개의 구간으로 나눠 그래프에 데이터가 들어가도록 세팅해둔 상태**입니다.
- 단순히 그래프를 그려주기 위해 데이터의 개수만 필요한데, 현재는 "내가 가진 도전에 대한 ConfirmPost 데이터를 모두 들고와 List에 담은 뒤에, 원하는 구간에 대한 List의 length를 이용하는 방식"이 비효율적이라고 느껴짐. 
→ 요 방식에서 '개수'만 가져오도록 하는 개선 방법이 있을까요?
- 이후에 각 도전 목표에 대한 상세 페이지가 만들어지는 경우에는 해당 페이지에서 요 데이터를 가져가서 쓸 수 있기 때문에 유용하겠지만, 
그럼에도 목표별 상세 페이지에 들어가기 이전에 모든 데이터를 fetch 하는게 어색하고 비효율적이라고 느껴집니다. ㅜㅜ
- 비고사항 읽어주세요~~
Close 
#119

[#119] feat: 마이페이지 뷰 UI에 그래프 데이터 연결

---

lib/common/routers/route_location.dart
lib/common/routers/route_provider.dart
lib/common/routers/route_provider.g.dart
lib/common/routers/test_page.dart
lib/features/live_writing_waiting/live_waiting_sample_view.dart
lib/features/live_writing_waiting/presentation/view/live_waiting_avatar_animation_widget.dart
lib/features/live_writing_waiting/presentation/view/live_waiting_view.dart
lib/features/live_writing_waiting/presentation/view/widget/live_waiting_avatar_animation_widget.dart

1. userImageUrl을 받아와서 위젯에 넣어주면 이미지를 그리도록 기능 구현
2. 간단한 애니메이션 적용
3. 적용 가능하도록 Stack으로 구조 빼서 작성하였음
- #110
- #5 
디자인
반영한 작업물
- `LiveWaitingAvatarAnimatingWidget(userImageUrl: imageUrl)` 의 형태로 사용할 수 있도록 만들었습니다.
- 실시간 대기 때 접속한 사용자들의 이미지를 받아와 리스트에 추가해주기만 하면 되어용!
- 사랑해요
Close #110

[#110] feat: 대기화면에 대한 UI 구조 간략 작성

---

lib/features/live_writing_waiting/live_waiting_sample_view.dart
lib/features/live_writing_waiting/presentation/view/live_waiting_view.dart
lib/features/live_writing_waiting/presentation/view/widget/live_waiting_avatar_animation_widget.dart

Provider를 사용하여, 외부에서 LiveWaitingView의 state에 userImageUrl을 추가하여 복잡한 콜백이나 접근 없이 쉽게 버블을 추가하는 로직을 구현할 수 있도록 개선하였음.
작업 내역을 설명하고 어떤 이슈와 관련되어 있는지 명시합니다.
Fixes #110 
작업 내역을 설명합니다.
LiveWaitingView 클래스에 적용 방법 및 버블 추가, 제거 방법 작성해두었음.
```
/// 실시간 인증 전 대기화면
/// 
/// ## 사용 방법
/// 1. Provider를 ref로 read 해준 뒤
/// ```
///   late LiveWaitingViewUserImageUrlList _imageUrlListProvider;
///   _imageUrlListProvider = ref.read(liveWaitingViewUserImageUrlListProvider.notifier);
/// ```
/// 2. LiveWritingView를 Stack에 담아주고
/// ```
/// Stack(
///   children: [ ... ,
///     LiveWritingView()
///   ...
///   ]
/// )
///
/// ```
/// 3. 아래처럼 urlString을 추가하는 함수를 호출해 화면에 버블을 그리거나 제거할 수 있음
/// ```
///   // 추가
///   _imageUrlListProvider.addUserImageUrl(imageUrl: 'urlString');
///   // 제거
/// …

[#110] fix: LiveWaitingView에 외부에서 버블을 추가할 수 있도록 구조 개선

---

ios/Podfile
ios/Podfile.lock
lib/features/live_writing/domain/models/confirm_post_model.dart
lib/features/live_writing/domain/models/confirm_post_model.freezed.dart
lib/features/live_writing/domain/models/confirm_post_model.g.dart
lib/features/live_writing_waiting/presentation/view/widget/live_waiting_avatar_animation_widget.dart
lib/features/my_page/data/datasources/resolution_remote_datasource_impl.dart
lib/features/my_page/presentation/widgets/resolution_linear_gauge_graph_widget.dart
lib/features/swipe_view/presentation/model/swipe_view_model.dart
lib/features/swipe_view/presentation/provider/swipe_view_confirm_post_list_provider.dart
lib/features/swipe_view/presentation/provider/swipe_view_model_provider.dart
lib/features/swipe_view/presentation/screen/swipe_view.dart
lib/features/swipe_view/presentation/screen/widget/swipe_dashboard_widget.dart
lib/features/swipe_view/presentation/screen/widget/swipe_view_cell.dart
pubspec.lock
pubspec.yaml

MyPage에서 작업했던 위젯을 기반으로 SwipeView에서 각 인증글에 대한 통계 정보를 간략하게 확인할 수 있도록 그래프 데이터 로직 작성하였음. 
- #119 을 기반으로
- #121 을 작업하였음.
Closes #119, #121 
- #119 에서 사용한 위젯 코드를 재사용하여 SwipeView에 적용
- 각 ConfirmPost에 대해 ConfirmPostList를 가져오는 로직을 작성
- View Constraint 수정으로 View Layout Exception이 발생하지 않도록 개선
|데이터 가져와 그래프 그려주기|키보드 여닫기에 대한 뷰 레이아웃 적용|
|---|---|
|![Simulator Screen Recording - iPhone 13 Pro - 2023-11-22 at 20 14 27](https://github.com/cau-bootcamp/wehavit/assets/39216546/c7ee7c8a-c5e2-4efc-940f-dfcce7006600)|![Simulator Screen Recording - iPhone 13 Pro - 2023-11-22 at 20 25 54](https://github.com/cau-bootcamp/wehavit/assets/39216546/51ca6340-1bc5-4d5f-96fa-57465c5e1ad1)|
- ConfirmPostModel의 resolutionId가 DocumentReference type으로 "\users\USER_ID\resolutions\RESOLUTION_ID" 의 형태로 저장되어 있는 부분을 String type으로 …

[#121] feat: SwipeView에 통계창 연결하기 

---

ios/Podfile.lock
lib/common/routers/route_location.dart
lib/common/routers/route_provider.dart
lib/common/routers/route_provider.g.dart
lib/common/routers/test_page.dart
lib/common/utils/firebase_collection_name.dart
lib/features/late_writing/domain/usecase/get_my_resolution_list_usecase.dart
lib/features/late_writing/domain/usecase/post_late_confirm_post_usecase.dart
lib/features/late_writing/presentation/model/late_writing_view_model.dart
lib/features/late_writing/presentation/provider/late_writing_view_provider.dart
lib/features/late_writing/presentation/screen/late_writing_view.dart
lib/features/my_page/data/datasources/resolution_remote_datasource_impl.dart
lib/features/my_page/presentation/providers/my_page_resolution_list_provider.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

인증글을 늦게 작성하는 경우에 인증글을 업로드하는 로직을 구현하기
- #92 로직을 참고하여 기능을 구현할 예정.
Related to #92 
Closes #102 
- 실시간 인증 방식 업로드 로직 활용해 늦은 인증글에 대한 repo, datasource 기능 작성
- 늦은 인증글 작성을 위한 디버깅용 테스트뷰 작성 및 검증
| | | |
|---|---|---|
|<img width="435" alt="image" src="https://github.com/cau-bootcamp/wehavit/assets/39216546/01c5aa65-46a9-4552-8e13-3796f82a9687">|<img width="479" alt="image" src="https://github.com/cau-bootcamp/wehavit/assets/39216546/500093ca-26b6-4e6b-81b9-a3e019c76364">|<img width="435" alt="image" src="https://github.com/cau-bootcamp/wehavit/assets/39216546/ea5577c6-7a13-4d7b-8b18-744f05882ee6">|
주형이가 작업중인 owner, fan, strike 부분 작업 끝나면 여기에도 동일하게 반영해주어야 함! 
```
late_writing_view_provider.dart 49번째 줄
// TODO: OWNER, FAN, ResentStrike 넣어주는 로직 작성 필요함
owner: '',
fan: [],
recentStrike: 0,
```

[#102] feat: 늦은글 인증 로직 구현

---

lib/features/reaction/presentation/provider/reaction_animation_widget_state_provider.dart
lib/features/reaction/presentation/widget/reaction_animation_widget.dart
lib/features/swipe_view/data/datasource/reaction_datasource_impl.dart
lib/features/swipe_view/presentation/provider/swipe_view_model_provider.dart
lib/features/swipe_view/presentation/screen/swipe_view.dart

반응 전송 로직에 남아있던 여러 문제 사항 수정
Closes #151 
작업 내역을 설명합니다.
- 사진으로 반응 전송 시 프로필 사진으로만 버블을 보여주던 문제 수정
- 이모지 반응 남기면 다른 이모지를 보여주던 버그 수정
|촬영한 반응 남기기|
|---|
|![Simulator Screen Recording - iPhone 13 Pro - 2023-12-03 at 15 13 34](https://github.com/cau-bootcamp/wehavit/assets/39216546/9d569d94-3353-4f95-8151-214f74f74bd5)|
이모지 리스트를 파이어베이스에서 가져왔을 때 List라 생각하고 index 접근을 시도했는데, map 형식으로 들어오면 정렬이 안된채로 그대로 index 접근으로 이상한 이모지를 가져오는 문제가 있었음 → 정렬을 위해 파이어베이스의 이모지 번호 형식을 변경함.

[#151] fix: 반응 전송 기능 수정

---

lib/features/late_writing/presentation/provider/late_writing_view_provider.dart
lib/features/late_writing/presentation/screen/late_writing_view.dart
lib/features/live_writing/data/datasources/confirm_post_remote_datasource.dart
lib/features/live_writing/data/datasources/confirm_post_remote_datasource_impl.dart
lib/features/live_writing/data/repositories/confirm_post_repository_impl.dart
lib/features/live_writing/presentation/widgets/my_live_writing_widget.dart

늦은 인증 글 작성시 혹은 실시간 인증글 작성 시에 owner 및 fan 정보를 같이 저장합니다.
fan정보는 기존의 resolution의 것을 가져옵니다.
이미 인증글이 존재하는 경우 덮어씁니다.
Closes #146 
관련 내용에 체크해주세요.
작업 내역을 설명합니다.
(ex. 나중에 수정해야 할 부분, 참고한 사이트, 참고한 코드 등)

[#146] feat: add fans when late/live confirm post upload 

---

lib/features/live_writing/data/repositories/live_writing_mine_repository_impl.dart
lib/features/live_writing/presentation/providers/active_resolution_provider.dart
lib/features/live_writing/presentation/screens/live_writing_view.dart
lib/features/live_writing_waiting/domain/models/waiting_model.dart
lib/features/live_writing_waiting/presentation/view/live_waiting_view.dart

실시간 인증 글 작성은 10시부터 5분입니다.
5분 타이머가 추가되었고 작성 시간으로부터 5분이 경과되면 창을 메인화면으로 이동합니다.
그리고 작업을 하며 발견한 버그를 두 가지 수정했습니다.
- 버그1. resolution 없는 경우 값이 초기화되어 페이지 크래쉬.
- 버그2. resolution 추가해도 앱을 껐다킬때까지 인증글이 목록 리스트에 추가가 안 됨.
Fixes #157 
관련 내용에 체크해주세요.
작업 내역을 설명합니다.
(버그 추정)
- 메인뷰에서 내가 남긴 글이 바로 보여야 되는데 보이지 않는 것 같아요!

[#157] 실시간 인증글 작성 시 타이머 로직 추가

---

ios/Podfile.lock
lib/data/datasources/firebase_datasource_impl.dart
lib/data/datasources/wehavit_datasource.dart
lib/data/repositories/reaction_repository_impl.dart
lib/domain/repositories/reaction_repository.dart
lib/domain/usecases/send_comment_reaction_to_confirm_post_usecase.dart
lib/domain/usecases/send_emoji_reaction_to_confirm_post_usercase.dart
lib/domain/usecases/send_quickshot_reaction_to_confirm_post_usecase.dart
lib/presentation/effects/camera_quickshot/reaction_camera_widget.dart
lib/presentation/home/screens/home_screen.dart
lib/presentation/home/widget/confirm_post_widget.dart
lib/presentation/reaction/provider/reaction_animation_widget_state_provider.dart
lib/presentation/reaction/widget/reaction_animation_widget.dart

HomeView에서 Quickshot 촬영을 위해 Pan Gesture 을 사용하면, 버튼이 정지하는 문제가 있어, 해당 기능이 동작하도록 수정하였음
Closes #193 
- 버그 수정
정상적으로 HomeView 의 pan gesture indicator가 작동함
코드 한 줄 수정하면 되는 문제였음! 
setState 시 하위 뷰 redraw → Key 문제로 하위 뷰를 새로 그리면서 pangesture가 붙어있는 위젯 자체가 새로 만들어져 발생한 문제

[#193] fix: home view pan gesture 작동 수정

---

lib/data/datasources/firebase_datasource_impl.dart
lib/data/datasources/wehavit_datasource.dart
lib/data/repositories/group_repository_impl.dart
lib/data/repositories/resolution_repository_impl.dart
lib/dependency/domain/usecase_dependency.dart
lib/domain/entities/entities.dart
lib/domain/entities/group_weekly_report_entity/group_weekly_resport_entity.dart
lib/domain/repositories/group_repository.dart
lib/domain/usecases/get_group_weekly_report_usecase.dart
lib/domain/usecases/usecases.dart
lib/presentation/test_view/group/group_sample_view.dart

작업 내역을 설명하고 어떤 이슈와 관련되어 있는지 명시합니다.
Fixes #
Closes #208 
Resolves #
- 일주일간의 그룹원들의 작업 통계를 확인하기 위한 데이터를 만드는 로직 구현
ReportEntity 하위에 ReportCell을 두었음 
Report Cell
- memberEntity : 어떤 유저의 정보인지)
- memberResolutionList : 이 유저가 공유한 목표 리스트)
- memberSuccessResolutionMap : 각 목표에 대한 성공/실패 여부를 {목표ID:T/F}의 형태로 보여줌
- doneResolutionIdListForEachDay : 각 요일 별로 인증한 목표id를 담은 List의 List
```
class GroupWeeklyReportEntity {
String groupId;
List<GroupWeeklyReportCell> groupWeeklyReportCellList;
}
class GroupWeeklyReportCell {
UserDataEntity memberEntity;
List<ResolutionEntity> memberResolutionList;
Map<String, bool> memberSuccessResolutionMap;
List<List<String>> doneResolutionIdListForEachDay;
}
```
(ex. 나중에 수정해야 할 부분, 참고한 사이트, 참고한 코드 등)

[#208] feat: 그룹 내 일주일 간의 각각의 인증글에 대한 통계를 전달하는 로직 구현

---

lib/common/common.dart
lib/common/utils/datetime+.dart
lib/data/datasources/firebase_datasource_impl.dart
lib/data/datasources/wehavit_datasource.dart
lib/data/models/firebase_models/resolution_model/firebase_resolution_model.dart
lib/data/repositories/confirm_post_repository_impl.dart
lib/data/repositories/resolution_repository_impl.dart
lib/domain/repositories/resolution_repository.dart
lib/domain/usecases/get_target_resolution_done_count_for_week_usecase.dart
lib/domain/usecases/upload_confirm_post_usecase.dart
lib/presentation/group_post/view/group_post_view.dart
lib/presentation/group_post/view/group_post_view_widget.dart
lib/presentation/write_post/provider/resolution_list_view_model_provider.dart
lib/presentation/write_post/provider/writing_confirm_post_view_model_provider.dart
lib/presentation/write_post/view/resolution_list_view_widget.dart
lib/presentation/write_post/view/writing_confirm_post_view.dart

인증글 카드의 달성 게이지 UI가 정상적으로 출력될 수 있도록 개선 + 이를 위해 내부 로직을 일부 수정함
Fixes #
Closes #227
Resolves #
- 인증글 카드 달성 게이지가 보여지도록 하기 위해 ConfirmPostEntity 에 데이터 추가
- 인증글 달성 게이지의 비율이 정상적으로 보이도록 View 코드 수정
- 지난 날짜 인증글 남기기 기능 정상적으로 동작
- 인증글 본문이 정상적으로 파이어베이스로 업로드됨
|이미지|GIF|
|---|---|
|<img width="300" alt="image" src="https://github.com/cau-bootcamp/wehavit/assets/39216546/2610df81-aef9-449b-bd51-d22e08e8aae4">|![Simulator Screen Recording - iPhone 13 Pro - 2024-05-10 at 09 15 56](https://github.com/cau-bootcamp/wehavit/assets/39216546/d518d272-6c67-410b-8250-8ff7cbb2253e)|
주어진 Date에 대해서 해당 Date가 들어있는 주의 월요일날의 00:00:00에 해당하는 DateTime을 만들어내는 함수를 DateTime Extension으로 추가해주었음. 상속 키워드인 extends와 확장 키워드인 extension 가 비슷해서인지 class extend를 검색했을 때 잘 안나와서 extension이 없나? 생각하고 있었는데, 다시 찾아보니 extension 키워드가 있어 적용해주었음. 유틸리티 …

[#227] feat: 인증글 카드의 달성 게이지 적용 및 기타 로직 수정

---

lib/presentation/common_components/resolution_list_cell_widget.dart
lib/presentation/effects/camera_quickshot/reaction_camera_widget.dart
lib/presentation/friend_list/view/friend_list_view.dart
lib/presentation/group/view/group_list_view_cell_widget.dart
lib/presentation/group/view/group_view.dart
lib/presentation/group_post/model/group_post_view_model.dart
lib/presentation/group_post/provider/group_post_view_model_provider.dart
lib/presentation/group_post/view/confirm_post_photo_view.dart
lib/presentation/group_post/view/group_member_list_view_widget.dart
lib/presentation/group_post/view/group_post_view.dart
lib/presentation/group_post/view/group_post_view_widget.dart
lib/presentation/write_post/model/resolution_list_view_model.dart
lib/presentation/write_post/provider/resolution_list_view_model_provider.dart
lib/presentation/write_post/view/resolution_list_view.dart
lib/presentation/write_post/view/writing_confirm_post_view.dart
pubspec.yaml

그룹뷰, 그룹포스트뷰의 UI와 관련해 필요한 부분들의 개선을 진행 및 미구현된 기능 구현
Fixes #
Closes #239 
Resolves #
- 그룹포스트뷰 뒤로가기 버튼 추가 및 미구현 버튼 주석처리
- 캘린더 접기/펼치기 구현
- 그룹포스트 데이터 로드 및 비동기 UI 로직 개선
- 포스트 사진 갤러리뷰 기능 구현
|그룹포스트뷰 UI 개선|캘린더 접고펼치기|
|---|---|
|![Simulator Screen Recording - 13 Pro simulator - 2024-06-10 at 16 04 09](https://github.com/cau-bootcamp/wehavit/assets/39216546/01d4d791-d22e-4032-804d-818259687866)|![Simulator Screen Recording - 13 Pro simulator - 2024-06-10 at 16 06 31](https://github.com/cau-bootcamp/wehavit/assets/39216546/d909f455-df5c-424b-953d-5714c1d351d1)|
실수로 #240의 기능 하나를 여기에서 개선하여 적용하였음!

[#239] fix: 그룹뷰, 그룹포스트뷰 UI 및 로직 개선

---

lib/presentation/group_post/view/group_post_view.dart

그룹포스트뷰 로드 시점에 바로 참가신청인원 배지 보여주도록 수정
Fixes #257
Closes #
Resolves #
- #258 PR에서 놓친 커밋 추가
실수했어요... 녹화만 따고 커밋 push를 안했어요...

[#257] fix: 그룹포스트뷰 로드 시점에 바로 참가신청인원 배지 보여주도록 수정

---

lib/data/datasources/auth_social_datasource.dart
lib/data/datasources/auth_social_datasource_impl.dart
lib/data/repositories/auth_repository_impl.dart
lib/domain/repositories/auth_repository.dart
lib/domain/usecases/log_in_with_apple_usecase.dart
lib/domain/usecases/log_in_with_email_and_password_usecase.dart
lib/domain/usecases/log_in_with_google_usecase.dart
lib/presentation/entrance/provider/auth_notifier.dart
lib/presentation/entrance/provider/log_in_view_model_provider.dart
lib/presentation/entrance/view/log_in_view.dart

애플 로그인 시 이름 바로 받아와 회원가입 정보 입력란에 넣어주도록 기능 구현하기
Fixes #
Closes #277 
Resolves #
- 애플 로그인으로 데이터 받아오기
- 받아온 데이터 뷰에 넘겨주기
- 넘겨준 데이터 뷰에 정상적으로 띄워서 보여주기
Sign in with Apple 로 회원가입을 하는 경우에는, 아래와 같은 방식으로 계정 정보를 가져오게 된다. 
```
final appleCredential = await SignInWithApple.getAppleIDCredential(
scopes: [
AppleIDAuthorizationScopes.email,
AppleIDAuthorizationScopes.fullName,
],
);
```
근데, 매우매우 유의할 점!이 있는데, 여기에서 개인정보 보호 정책상 appleCredential 을 통해서 사용자 ID 외에 이메일, 이름 등의 다른 정보들은 **"서비스에 처음으로 계정을 접속시킬 때"**에만 불러올 수 있다. 즉, 이름이나 이메일 같은 데이터를 애플 로그인 시에 가져오고 싶다면, 따로 서비스나 캐시에 저장해두고 사용자ID 값을 key로 하여 해당 데이터를 관리해야한다. 이외의 시점에는 appleCredential의 다른 데이터들은 모두 null이 들어있고 사용자ID만 딱 들어있게된다. 
요 부분은 나중에도 주의가 필요한 부분임!!

[#277] feat: 애플 로그인 시 이름 바로 받아와 회원가입 정보 입력란에 넣어주도록 구현

---

.gitignore
ios/Runner.xcodeproj/project.pbxproj
lib/data/datasources/auth_social_datasource.dart
lib/data/datasources/auth_social_datasource_impl.dart
lib/data/datasources/firebase_datasource_impl.dart
lib/data/repositories/auth_repository_impl.dart
lib/dependency/domain/usecase_dependency.dart
lib/dependency/presentation/viewmodel_dependency.dart
lib/domain/repositories/auth_repository.dart
lib/domain/usecases/revoke_apple_sign_in_usecase.dart
lib/domain/usecases/usecases.dart
lib/main.dart
lib/presentation/entrance/view/edit_user_detail_view.dart
lib/presentation/my_page/provider/my_page_view_model_provider.dart
lib/presentation/my_page/view/my_page_view.dart
pubspec.yaml

회원 탈퇴 시 계정 삭제 로직을 구현함
Fixes #
Closes #278 
Resolves #
- 회원 탈퇴 기능 구현
- 애플 계정으로 회원가입 시 애플로그인으로 인증 후 탈퇴
- 구글 계정/이메일로 회원가입 시 바로 탈퇴 
|회원탈퇴(Google / 이메일)|회원탈퇴(Apple)|애플회원탈퇴 시 메일|
|---|---|-----|
|<img src="https://github.com/cau-bootcamp/wehavit/assets/39216546/6571c575-92e6-460b-8a9c-409721d0bfe6" width=200>|<img src="https://github.com/cau-bootcamp/wehavit/assets/39216546/056f84c9-2d90-4bc0-af97-10b2268464f5" width=200>|<img width="500" alt="image" src="https://github.com/cau-bootcamp/wehavit/assets/39216546/63cfb4c4-22c3-4998-aa62-0e1002c60979">|
회원탈퇴를 바닐라Dart 로 구현하기 위해서 꽤나 고생을 좀 했다. 생각보다 바닐라 Dart로 이를 구현해둔 예제가 없었고, 다들 Spring, Java 등으로 우회해서 처리하는 곳이 많았음. 그래서 닥치는대로 자료를 찾아보고 공부해서 Dart 만으로 로그아웃을 구현하는 코드를 작성했음! 아래 참고하기.
https://etst.tistory.com/383
애플 회원탈퇴 시 애플 서버에 이를 알려야하는데, 여기에 사용되는 Private Key를 …

[#278] feat: 계정 삭제 기능 구현

---

lib/presentation/effects/camera_quickshot/reaction_camera_widget_model_provider.dart

앱 내에서 사용하지 않는 카메라의 마이크 기능으로 인해 그룹 뷰 진입 시 앱이 꺼지는 문제가 발생하고 있음.
앱 크래시가 발생하고 있어서, 빠르게 수정 후 재배포 예정
Fixes #
Closes #286 
Resolves #
- 마이크 기능 해제하기
문제 해결을 위해서 2가지 방법이 있었고, 더 타당하다고 생각되는 마이크 사용 기능을 제거하는 방식을 선택하여 수정함.
- 마이크 사용 권한 부여하기
- 앱 내 마이크 사용을 제거하기
어떻게 심사를 통과한거지...?

[#286] HOTFIX: 반응남기기용 카메라 기능에서 마이크 사용하지 않도록 제거

---

lib/dependency/presentation/viewmodel_dependency.dart
lib/presentation/my_page/view/my_page_view.dart
lib/presentation/write_post/provider/add_resolution_done_view_model_provider.dart
lib/presentation/write_post/view/add_resolution_done_view.dart

친구, 그룹 등 목표 공유대상을 수정하는 기능을 구현
Fixes #
Closes #292 
Resolves #
- 목표를 공유하는 친구 수정 기능 구현
- 목표를 공유하는 그룹 수정 기능 구현
현재 사용중인 마이페이지의 버튼은 통계페이지로 이동하기 위한 버튼임.
이후에 각 목표별 통계페이지 디자인이 나오고 해당 페이지를 구현하면 통계페이지 안으로 공유대상 수정 버튼을 이동시키기.

[#292] feat: 목표 공유대상 수정 기능 구현

---

lib/dependency/presentation/viewmodel_dependency.dart
lib/presentation/friend_list/view/friend_list_view.dart
lib/presentation/group/provider/group_view_model_provider.dart
lib/presentation/group/view/group_view.dart
lib/presentation/main/view/main_view.dart
lib/presentation/my_page/view/my_page_view.dart
lib/presentation/write_post/view/resolution_list_view.dart

작업 내역을 설명하고 어떤 이슈와 관련되어 있는지 명시합니다.
Fixes #
Closes #295 
Resolves #
- ResolutionList ViewModel의 데이터 로드 함수 → MainView 로 이동
- GroupList ViewModel의 데이터 로드 함수 → MainView 로 이동
- FriendList ViewModel의 데이터 로드 함수 → MainView 로 이동
- MyPage ViewModel의 데이터 로드 함수 → MainView 로 이동
PR을 작성하면서 요 작업의 태그가 refactor가 더 적절하다는걸 늦게 알았다. ㅋㅋㅎ
현재 각 뷰모델이 해당 뷰의 데이터와 밀접하게 관련되어있음. 그렇다보니 같은 데이터도 여러 뷰에서 로드해서 자신의 영역에서 사용하는 문제가 있다. 
현재는 내 정보 → 목표리스트 / 친구 / 마이페이지 모두에서 따로 로드해서 사용하고 있음 ... 근데 이걸 한 번만 로드해오고 각자가 MyUserData source에 접근하여 값을 가져가는 방식으로 구현하면 훨씬 쿼리를 덜 사용하도록 개선이 가능하다. 
이후에 리팩토링을 진행하면서 데이터를 좀 더 공유하면서 사용할 수 있는 방식으로 개선이 필요할 것 같다. 캐싱 데이터를 저장하는 공간을 공유메모리 공간으로 사용할 수도 있을 듯!

[#295] refactor: viewmodel 들의 데이터 로드 시점을 MainView 로드 시점으로 옮기기

---

ios/Podfile
ios/Podfile.lock
lib/presentation/group_post/view/group_post_view_widget.dart

리액션을 전송한 뒤, 이에 대한 피드백으로 토스트메시지를 출력합니다.
Fixes #
Closes #322
Resolves #
- 리액션 전송 후 토스트메시지를 출력하도록 변경

[#322] feat: 리액션 전송 후 토스트메시지 띄우기

---

lib/presentation/common_components/show_toast_message.dart
lib/presentation/group_post/view/group_post_view_widget.dart

토스트메시지의 컴포넌트 디자인을 수정합니다.
Fixes #
Closes #320 
Resolves #
- 토스트메시지 vertical padding 값 조정
|변경 후|
|---|
|<img src="https://github.com/user-attachments/assets/62e20506-54c6-4d32-8b0f-eb284b30c92a" width=350>|
세로 높이를 직접 조정하는 대신 세로 padding 값을 줄여, 이후 변경으로 글자가 짤릴 가능성을 제거하였음

[#320] feat: 토스트메시지 컴포넌트 디자인 수정

---

lib/presentation/effects/emojis/balloon_animation/balloon_manager.dart
lib/presentation/effects/emojis/text_animation/text_bubble_widget.dart

리액션을 위한 ImageBubble의 시안성 향상을 위해, 버블 주위에 흰색 테두리를 추가합니다.
Fixes #
Closes #321 
Resolves #
- TextBubble에 테두리 추가
- ReactionBubbleImage에 테두리 추가
(ex. 나중에 수정해야 할 부분, 참고한 사이트, 참고한 코드 등)

[#321] feat: 리액션 버블에 테두리 추가

---

lib/presentation/group_post/view/group_post_view.dart
lib/presentation/my_page/view/resolution_detail_view.dart

기존에 무한히 과거로 스크롤이 가능했던 횡스크롤 달력에서
목표 / 그룹 생성일까지만 스크롤이 가능하며, 생성일 이전의 날짜는 비활성화되도록 로직을 수정합니다.
Fixes #
Closes #323
Resolves #
- 마이페이지의 목표별 횡스크롤 달력에서 로직 수정
- 그룹 횡스크롤 달력에서 로직 수정

feat: 달력 위젯의 과거 스크롤 제한 추가

---

lib/presentation/group_post/view/friend_post_view.dart
pubspec.yaml

ReactionCameraView의 로직 및 GroupPostView에서의 카메라뷰의 렌더링 조건을 변경하는 과정에서, 내 친구들 페이지의 카메라 렌더 조건을 변경하지 않아 사용에 문제가 발생하고 있었습니다. 본 PR로 해당 문제를 수정하였습니다. 
Fixes #
Closes #348 
Resolves #
- 내 친구들 페이지의 ReactionCameraView의 렌더링 조건을 변경하여, 정상적으로 작동할 수 있도록 수정하였습니다.
- v1.0.11으로 버전 정보를 변경하였습니다.
release 빌드 및 abb 파일 play console에 업로드 완료
(ex. 나중에 수정해야 할 부분, 참고한 사이트, 참고한 코드 등)

[#348] HOTFIX: 내 친구들 페이지 리액션카메라뷰 로드 조건 변경 및 버전업

---

lib/dependency/presentation/viewmodel_dependency.dart
lib/domain/usecases/send_comment_reaction_to_confirm_post_usecase.dart
lib/domain/usecases/send_emoji_reaction_to_confirm_post_usercase.dart
lib/domain/usecases/send_quickshot_reaction_to_confirm_post_usecase.dart
lib/presentation/common_components/my_profile_block.dart
lib/presentation/common_components/my_wehavit_summary.dart
lib/presentation/common_components/user_profile_cell.dart
lib/presentation/friend_list/model/friend_list_view_model.dart
lib/presentation/friend_list/provider/friend_list_view_model_provider.dart
lib/presentation/friend_list/view/friend_list_view.dart
lib/presentation/group_post/view/group_post_view_widget.dart
lib/presentation/main/view/main_view.dart
lib/presentation/my_page/model/my_page_view_model.dart
lib/presentation/my_page/provider/my_page_view_model_provider.dart
lib/presentation/my_page/view/my_page_view.dart
lib/presentation/state/user_data/my_user_data_provider.dart
lib/presentation/write_post/view/resolution_list_view.dart
lib/presentation/write_post/view/writing_confirm_post_view.dart

내 사용자 정보(UserEntity)를 공용 상태로 관리하며, 화면에서 하나의 State를 공유하도록 변경합니다.
Fixes #
Closes #353 
Resolves #
- 사용자 정보를 공용 State (myUserDataStateProvider) 에서 관리
- 탭바, 친구목록, 마이페이지에서 해당 State에 접근해 사용하도록 변경
공용 State 추가 및 화면 전환을 하더라도 내 정보를 가져오는 Usecase는 한 번만 호출하도록 구현하였음
내 사용자정보 State를 AutoDispose 로 설정하는 경우, 탭 전환 시 마다 새로 UserState를 불러오는 Usecase를 호출하면서, 안하느니만 못하는 문제가 발생함. (watch로 구독하는 화면이 하나도 없어서 이렇게 되는 것 같다.)
그래서 앱 실행하는 동안 계속 유지되어야 하는 상태이기에 AutoDispose 처리를 해주지 않았음.

[#353] feat: 나의 UserEntity 를 공용 State로 변경

---

lib/dependency/presentation/viewmodel_dependency.dart
lib/domain/usecases/get_target_resolution_done_list_for_week_usecase.dart
lib/presentation/common_components/circular_status_indicator.dart
lib/presentation/common_components/resolution_linear_gauge_indicator.dart
lib/presentation/common_components/resolution_list_cell.dart
lib/presentation/common_components/wh_icon.dart
lib/presentation/group_post/view/friend_list_bottom_sheet_widget.dart
lib/presentation/group_post/view/group_post_view_widget.dart
lib/presentation/my_page/view/my_page_view.dart
lib/presentation/my_page/view/resolution_detail_view.dart
lib/presentation/state/resolution_list/resolution_list_provider.dart
lib/presentation/write_post/provider/resolution_list_view_model_provider.dart
lib/presentation/write_post/provider/writing_confirm_post_view_model_provider.dart
lib/presentation/write_post/view/add_resolution_done_view.dart
lib/presentation/write_post/view/resolution_list_view.dart

목표 목록을 공용 State로 분리해, 상태를 더욱 효율적으로 관리하고 유지할 수 있도록 변경합니다. 
Fixes #
Closes #357
Resolves #
- 목표 목록을 관리하는 State, Provider 추가
- 주간 목표 컴포넌트 수정
- Linear Gauge
- Weekly Status 
- 목표 추가 / 제거 시 상태 invalidate 코드 추가
작업 결과물을 첨부합니다. (ex. 스크린샷, gif, 다른 사람이 사용할 수 있는 ㅇㅇAPI 등)
기존의 EitherFuture 타입을 다루기 위해 사용했던 EitherFutureBuilder 위젯 대신에,
FutureProvider 의 결과인 비동기 데이터 타입 AsyncValue 를 이용하는 코드로 변경하고 있습니다. 
`AsyncValue.when`을 호출했을 때 로딩중, 에러, 완료 3가지 상태에 대해 각자 로직을 작성할 수 있어 동일한 효과를 줍니다.

[#357] refactor: 목표 목록을 공용 State로 변환 및 컴포넌트 수정

---

lib/presentation/main/view/main_view.dart
lib/presentation/main/view/main_view_widget.dart
lib/presentation/my_page/view/my_page_view.dart

네비게이션 탭바 버튼을 눌렀을 때 프로필이미지가 깜빡이는 문제를 제거하고 불필요한 코드를 제거합니다.
Fixes #
Closes #368 
Resolves #
- 네비게이션 탭바 버튼을 눌렀을 때 프로필이미지가 깜빡이는 문제 제거
- 네비게이션 탭바 UI를 디자인에 맞춰 수정
|기존|개선|
|---|---|
|![image](https://github.com/user-attachments/assets/d5595565-53e1-4a0d-8941-3beda9fc02d6)|![image](https://github.com/user-attachments/assets/9a4900c6-3c2b-4677-8c04-d936c9a55062)|

[#368] refactor: 네비게이션탭바 프로필이미지 깜빡임 제거

---

lib/common/constants/theme.dart
lib/common/utils/image_uploader.dart
lib/common/utils/isolate_helper.dart
lib/data/datasources/firebase_datasource_impl.dart
lib/dependency/domain/usecase_dependency.dart
lib/dependency/presentation/viewmodel_dependency.dart
lib/domain/usecases/get_target_resolution_done_list_for_week_usecase.dart
lib/domain/usecases/upload_confirm_post_image_usecase.dart
lib/domain/usecases/upload_confirm_post_usecase.dart
lib/main.dart
lib/presentation/common_components/confirm_post_list_cell.dart
lib/presentation/common_components/resolution_linear_gauge_indicator.dart
lib/presentation/common_components/resolution_list_cell.dart
lib/presentation/common_components/upload_photo_bottom_toolbar.dart
lib/presentation/common_components/upload_photo_cell.dart
lib/presentation/common_components/weekly_resolution_summary_card.dart
lib/presentation/my_page/view/resolution_detail_view.dart
lib/presentation/state/group_post/friend_post_provider.dart
lib/presentation/state/resolution_list/resolution_list_provider.dart
lib/presentation/write_post/model/writing_confirm_post_view_model.dart
lib/presentation/write_post/provider/add_resolution_view_model_provider.dart
lib/presentation/write_post/provider/resolution_list_view_model_provider.dart
lib/presentation/write_post/provider/writing_confirm_post_view_model_provider.dart
lib/presentation/write_post/view/add_resolution_done_view.dart
lib/presentation/write_post/view/add_resolution_view.dart
lib/presentation/write_post/view/resolution_list_view.dart
lib/presentation/write_post/view/resolution_list_view_widget.dart
lib/presentation/write_post/view/writing_confirm_post_view.dart
lib/presentation/write_post/view/writing_confirm_post_view_widget.dart

인증글 작성하기 페이지의 상태를 분리하고, UI를 리디자인으로 개선합니다.
Fixes #
Closes #367 
Resolves #
- 인증글 작성하기 메뉴 UI 개선
- 인증글 작성 페이지 UI 및 사진 업로드 로직 개선
- 공유 대상 확인 페이지 UI 및 상태 개선
- 도전 추가하기 UI 변경 및 로직 개선
- 기타 다른 페이지의 동작 이상 개선
- 목표상세 페이지의 내가 쓴 인증글 목록 제대로 보여주도록 개선
- 새로고침 시 상태 초기화 로직 추가
|인증글 작성 메뉴|인증글 작성 페이지|공유 대상|도전 추가|
|---|---|---|---|
|![Screenshot_20250214_104219](https://github.com/user-attachments/assets/2ffeec86-eb95-4abb-8949-0eb4563c79fc)|![Screenshot_20250214_104450](https://github.com/user-attachments/assets/1fe235f7-1928-4bd1-be50-80e02f728bfc)|![Screenshot_20250214_104457](https://github.com/user-attachments/assets/ac56e657-45fa-4d84-aa5a-53bf8d5728f4)|![Screenshot_20250214_104726](https://github.com/user-attachments/assets/72d0c3e6-6d8f-4250-938f-1ddc2617843e)|
화이팅!

[#367] refactor: 인증글 작성하기 페이지 UI 개선 및 상태 수정

---

lib/presentation/common_components/weekly_swipe_calendar.dart
lib/presentation/write_post/view/resolution_list_view_widget.dart
lib/presentation/write_post/view/writing_confirm_post_view.dart

QA 에서 발견된 버그를 수정합니다.
Fixes #
Closes #377, #380, #383, #384
Resolves #
- 인증글 업로드 후에도 이번 주 인증글 현황이 업데이트되지 않는 문제 → 업로드 시 State invalidate 코드를 추가하여 해결
- 인증 남기기 iOS 화면에서 아래쪽 레이아웃이 SafeArea 적용되지 않았던 문제 해결
- 인증글 재작성 시 이미 작성된 글이 있다는 다이얼로그 추가
- 가로 스크롤 캘린더의 초기 날짜가 시간을 포함한 경우 (00:00:00이 아닌 경우) 해당 날짜를 미포함하는 문제 해결
|다이얼로그 추가|레이아웃 수정|
|---|---|
|![Simulator Screenshot - iPhone 15 Pro - 2025-03-07 at 15 46 49](https://github.com/user-attachments/assets/d3692c14-af78-4613-aa97-969591caba51)|![Simulator Screenshot - iPhone 15 Pro - 2025-03-07 at 15 46 56](https://github.com/user-attachments/assets/a4857c9e-d868-4bee-ae0d-ff45a0c76589)|

[#377, #380, #383, #384] fix: QA 리포트 1차 반영

---

lib/domain/usecases/send_notification_to_shared_users_usecase.dart
lib/domain/usecases/send_notification_to_target_user_usecase.dart

알림 로직에서 나를 타겟으로 알림을 전송하지 않도록 수정합니다. 
Fixes #
Closes #382 
Resolves #
- 리액션에 대한 알림 전송 Usecase 내에 타겟 필터링 추가
- 게시글에 대한 알림 전송 Usecase 내에 타겟 필터링 추가
내가 포함된 그룹에 글을 작성하거나 나에게 스스로 리액션을 전송하더라도 내 게시글에 대한 알림을 받지 않습니다.

[#382] fix: 알림 전송 Usecase에서 나에게 알림 전송하지 않도록 수정

---

lib/presentation/common_components/confirm_post_list_cell.dart
lib/presentation/common_components/my_profile_block.dart
lib/presentation/friend_list/view/friend_list_view.dart
lib/presentation/my_page/view/my_page_view.dart

로그아웃, 친구 삭제, 퀵샷 삭제 로직과 같은 Destructive 액션의 로직을 수행하기 앞서, Dialog UI를 띄워 사용자에게 확인을 받도록 개선하였습니다.
Fixes #
Closes #379 
Resolves #
- 로그아웃 시 다이얼로그 띄우기
- 친구 삭제 시 다이얼로그 띄우기
- 퀵샷 삭제 시 다이얼로그 띄우기
|로그아웃|친구삭제|퀵샷삭제|
|---|---|---|
|![Simulator Screenshot - iPhone 15 Pro - 2025-03-20 at 20 28 14](https://github.com/user-attachments/assets/a9b3b988-6c2c-495c-8340-7b6a66fb2a8d)|![Simulator Screenshot - iPhone 15 Pro - 2025-03-20 at 20 28 09](https://github.com/user-attachments/assets/8f8f4149-c326-4a90-8a06-e0340a5a8c10)|![Simulator Screenshot - iPhone 15 Pro - 2025-03-20 at 20 28 01](https://github.com/user-attachments/assets/a62ca0a9-4c6c-42c9-b4f9-f8675bbd44a9)|
Flutter의 기본 Dialog (Material Design) 의 느낌이 플랫한 디자인과 어울리지 않아, 
우선 쿠퍼티노 Dialog로 UI 디자인을 통일하여 적용하였음.
이후에 안드로이드 쪽에서 디자인이 어색하다면 Dialog 컴포넌트 분리 및 …

[#379] fix: 로그아웃, 친구 삭제, 퀵샷 삭제 수행 전 Dialog를 띄우기
